version: "3.3"
services:
  api:
    build: ./api/.
    ports:
      - "8080:8080"
    links:
      - "database"

  database:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: loginBoiler
      MYSQL_USER: loginBoiler
      MYSQL_PASSWORD: loginBoilerpw

volumes:
  db-data:
